name: cogwiki.yaml.io
description: The YAML Wiki

url: http://cogwiki.yaml.io

#permalink: pretty
permalink: none

paginate: 20

markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md

# This is for {% highlight %} blocks
highlighter: rouge

safe: true
lsi: false

encoding: utf-8
timezone: America/Los_Angeles

github:
  project_title: cogwiki
  project_tagline: Experimental Wiki with Jekyll

gems:
- kramdown
- jemoji
- jekyll-sitemap
- jekyll-coffeescript
- jekyll-paginate
- jekyll-redirect-from
- jekyll-mentions

kramdown:
  input: GFM
  hard_wrap: false
  # This is for fenced code blocks: ~~~
  syntax_highlighter: rouge

defaults:
- scope:
    path: ""     # an empty string here means all files in the project
    type: posts  # "post" for Jekyll <=2.2
  values:
    language: en

